package setup

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const daemonEnvFileName = "daemon.env"

func DaemonEnvironmentFilePath(setupPath string) string {
	setupPath = strings.TrimSpace(setupPath)
	if setupPath == "" {
		if defaultPath, err := DefaultConfigPath(); err == nil {
			setupPath = defaultPath
		}
	}
	if setupPath == "" {
		return daemonEnvFileName
	}
	return filepath.Join(filepath.Dir(filepath.Clean(setupPath)), daemonEnvFileName)
}

func ImportDaemonEnvironmentFile(setupPath string, cfg Config) error {
	values, err := loadDaemonEnvironmentFile(DaemonEnvironmentFilePath(setupPath))
	if err != nil {
		return err
	}
	for _, name := range daemonEnvironmentNames(cfg) {
		value := strings.TrimSpace(values[name])
		if value == "" {
			continue
		}
		if err := os.Setenv(name, value); err != nil {
			return fmt.Errorf("set daemon environment %s: %w", name, err)
		}
	}
	return nil
}

func writeDaemonEnvironmentFile(setupPath string, cfg Config) (string, bool, error) {
	path := DaemonEnvironmentFilePath(setupPath)
	names := daemonEnvironmentNames(cfg)
	if len(names) == 0 {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return path, false, fmt.Errorf("remove daemon environment file: %w", err)
		}
		return path, false, nil
	}

	existing, err := loadDaemonEnvironmentFile(path)
	if err != nil {
		return path, true, err
	}
	values, missing := daemonEnvironmentValues(names, existing)
	if len(missing) > 0 {
		return path, true, fmt.Errorf("daemon provider environment variable %s is required; export it and re-run setup", strings.Join(missing, ", "))
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return path, true, fmt.Errorf("create daemon environment dir: %w", err)
	}
	data := renderDaemonEnvironmentFile(names, values)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(data), 0o600); err != nil {
		return path, true, fmt.Errorf("write daemon environment file: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return path, true, fmt.Errorf("install daemon environment file: %w", err)
	}
	if err := os.Chmod(path, 0o600); err != nil {
		return path, true, fmt.Errorf("secure daemon environment file: %w", err)
	}
	return path, true, nil
}

func daemonEnvironmentNames(cfg Config) []string {
	seen := map[string]struct{}{}
	for _, provider := range cfg.Providers {
		if strings.TrimSpace(provider.APIKey) != "" {
			continue
		}
		envName := providerAPIKeyEnvName(provider)
		if !validEnvironmentName(envName) {
			continue
		}
		seen[envName] = struct{}{}
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func daemonEnvironmentValues(names []string, existing map[string]string) (map[string]string, []string) {
	values := make(map[string]string, len(names))
	missing := []string{}
	for _, name := range names {
		if value := strings.TrimSpace(os.Getenv(name)); value != "" {
			values[name] = value
			continue
		}
		if value := strings.TrimSpace(existing[name]); value != "" {
			values[name] = value
			continue
		}
		missing = append(missing, name)
	}
	return values, missing
}

func renderDaemonEnvironmentFile(names []string, values map[string]string) string {
	var b strings.Builder
	b.WriteString("# Generated by matrixclaw setup. Contains provider secrets; keep mode 0600.\n")
	for _, name := range names {
		b.WriteString(name)
		b.WriteByte('=')
		b.WriteString(quoteDaemonEnvironmentValue(values[name]))
		b.WriteByte('\n')
	}
	return b.String()
}

func loadDaemonEnvironmentFile(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return map[string]string{}, nil
		}
		return nil, fmt.Errorf("read daemon environment file: %w", err)
	}

	values := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, rawValue, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		name = strings.TrimSpace(name)
		if !validEnvironmentName(name) {
			continue
		}
		values[name] = unquoteDaemonEnvironmentValue(strings.TrimSpace(rawValue))
	}
	return values, nil
}

func daemonProcessEnvironment(setupPath string, cfg Config) []string {
	env := os.Environ()
	values, _ := loadDaemonEnvironmentFile(DaemonEnvironmentFilePath(setupPath))
	names := daemonEnvironmentNames(cfg)
	for _, name := range names {
		value := strings.TrimSpace(os.Getenv(name))
		if value == "" {
			value = strings.TrimSpace(values[name])
		}
		if value != "" {
			env = append(env, name+"="+value)
		}
	}
	env = append(env, "MATRIXCLAW_SETUP_PATH="+setupPath)
	return env
}

func quoteDaemonEnvironmentValue(value string) string {
	value = strings.TrimSpace(value)
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\"", "\\\"")
	value = strings.ReplaceAll(value, "\n", "")
	value = strings.ReplaceAll(value, "\r", "")
	return `"` + value + `"`
}

func unquoteDaemonEnvironmentValue(value string) string {
	if len(value) >= 2 && strings.HasPrefix(value, `"`) && strings.HasSuffix(value, `"`) {
		value = strings.TrimSuffix(strings.TrimPrefix(value, `"`), `"`)
		value = strings.ReplaceAll(value, `\"`, `"`)
		value = strings.ReplaceAll(value, `\\`, `\`)
	}
	return strings.TrimSpace(value)
}

func validEnvironmentName(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return false
	}
	for i, r := range name {
		switch {
		case r == '_':
		case r >= 'A' && r <= 'Z':
		case r >= 'a' && r <= 'z':
		case i > 0 && r >= '0' && r <= '9':
		default:
			return false
		}
	}
	return true
}
